Implement CsrfLayerBuilder to allow setting the cookie key
AscendingCreations/AxumCSRF pull request #2
Opened 2022-05-25 17:07 UTC by jdkaplan

I noticed that my authenticity tokens weren't working across server restarts because there's a new encryption key generated each time the `CsrfLayer` gets built. To mitigate that, I've added an option to set the key during the build. That way, I can use the same key I already have for other encrypted cookies.

I considered making the `CsrfLayer` fields real-public (instead of just crate-visible), but having the `CsrfLayerBuilder` felt like a less invasive change.

I'm still a novice in both Rust and Axum, so I'll be grateful for any feedback you have :)

2022-05-25 17:36 UTC, genusistimelord commented
I agree that making them public could be invasive and I only did it to prevent people from having to deal with Axums Extension wrapper directly. We could probably also make the Key publicly accessible so people can use it directly thru the lib too to generate a new key. That can always be for another push. Anyways it looks good just needs some Examples added to the Readme and to add some documentation Comments on what each function is for or does.  you can add it like `/// CSRF layer struct used to pass key and CsrfConfig around.`

2022-05-25 17:37 UTC, genusistimelord requested changes
Need to add an Example to Readme and Documentation Comments for the functions and Structure.  If you need help feel free to ask. I do have a discord group for this you can find me there or ask here.

2022-05-26 10:50 UTC, jdkaplan reviewed
I added some doc comments and a readme example. Let me know if you'd like me to rewrite anything or change the level of detail.

2022-05-26 10:50 UTC, jdkaplan commented on README.md
> +If you need help with this library please go to our [Discord Group](https://discord.gg/xKkm7UhM36)
Looks like my editor added the ending newline here, nothing more!

2022-05-26 11:40 UTC, genusistimelord approved these changes
Everything looks good!

2022-05-26 11:40 UTC, merged

2022-05-26 11:53 UTC, genusistimelord commented
I have merged and republished this into 0.4.0 on crates.io